# These are supported funding model platforms

github: Nathishwar-prog # Your GitHub Sponsors username
patreon:               # Optional: add if you have one
open_collective:
ko_fi: Nathishwar
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: Nathishwar
thanks_dev:
custom:                # Optional: add custom URLs like ['https://yourwebsite.com/sponsor']
